export { ClassesDummy } from './Classes.dummy'
export { Filled } from './Filled'
export { Outlined } from './Outlined'
export { CustomColor } from './CustomColor'
export { default as Canvas } from './Canvas'
