import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { ThemeProvider } from '@v-uik/theme'
import { theme } from './theme'
import { NextJsProvider } from '@v-uik/next-js-provider'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NextJsProvider>
          <ThemeProvider theme={theme}>{children}</ThemeProvider>
        </NextJsProvider>
      </body>
    </html>
  )
}
