export * from './Basic'
export * from './BasicTagInput'
export * from './ColorIndicator'
export * from './ColorTagsExample'
export * from './CustomColor'
export * from './DifferentSizeExample'
export * from './TagTypesExample'
export * from './Classes.dummy'
export * from './CanvasPolymorphic'
export * from './PolymorphicTag.Dummy'
export { default as Canvas } from './Canvas'
